# Generated by Django 6.0.6 on 2026-06-26 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Supplying company, if this product was listed by a vendor rather than the store admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='vendors.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Vendor-submitted products start unapproved until admin reviews them.'),
        ),
    ]
