# Generated by Django 6.0.6 on 2026-06-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('other', 'Other')], default='birthday', max_length=20)),
                ('date', models.DateField(help_text='The month and day repeat every year')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
