# Generated by Django 6.0.6 on 2026-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False, help_text='Account represents a company/supplier, not a shopper.'),
        ),
    ]
